CREATE TABLE [Customer].[Detail]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[CustomerId] INT NOT NULL DEFAULT dbo.GetCustomerId(),
	[FirstName] VARCHAR(64) NOT NULL,
	[LastName] VARCHAR(64) NOT NULL,
	[StreetNumber] INT NOT NULL,
	[Address1] VARCHAR(128) NOT NULL,
	[Address2] VARCHAR(128) NULL,
	[Address3] VARCHAR(128) NULL,
	[City] VARCHAR(64) NOT NULL,
	[State] VARCHAR(16) NOT NULL,
	[PostalCode] INT NOT NULL,
	[PrimaryPhone] VARCHAR(10) NOT NULL,
	[SecondaryPhone] VARCHAR(10) NULL,
	[EmailAddress] VARCHAR(512) NULL,
	[RowVersionDate] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[RowVersionUser] VARCHAR(64) NOT NULL DEFAULT SYSTEM_USER,
	[DeletedDate] DATETIME NULL,
	[RowCreatedDate] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	[RowCreatedUser] VARCHAR(64) NOT NULL DEFAULT SYSTEM_USER
);